// Generated by https://quicktype.io

export interface SendMessageOptions {
  chat_id: string;
  text: string;
}

export interface SendMessageRes {
  ok: boolean;
  result: Result;
}

export interface Result {
  message_id: number;
  from: From;
  chat: Chat;
  date: number;
  text: string;
}

export interface Chat {
  id: number;
  first_name: string;
  last_name: string;
  type: string;
}

export interface From {
  id: number;
  is_bot: boolean;
  first_name: string;
  username: string;
}
